<a href="https://colab.research.google.com/github/GuuhMatias/Colab/blob/main/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
M = np.array([[3,4,5],[1,2,3],[6,7,8]]) # lista aninhada colocada dentro de uma array

In [ ]:
M

array([[3, 4, 5],
       [1, 2, 3],
       [6, 7, 8]])

In [ ]:
type(M)

numpy.ndarray

In [ ]:
# Agora para transformar aquela lista em um objeto tipo matriz
M2 = np.matrix([[3,4,5],[1,2,3],[6,7,8]])

In [ ]:
M2

matrix([[3, 4, 5],
        [1, 2, 3],
        [6, 7, 8]])

In [ ]:
type(M2)

numpy.matrix

In [ ]:
# Para pesquisar um algoritmo dentro das colunas e das linhas, utilizamos colchetes + numero da linha
# + o numero da coluna

M[2,2]

8

In [ ]:
M[1,1]

2

In [ ]:
# E para procurar todos os elementos de uma linha, usamos os mesmos esquemas de procura de algoritmo
# de listas e etc

M[2:]

array([[6, 7, 8]])

In [ ]:
# Acima, pegamos todos os elementos de uma só linha

M[:2]

array([[3, 4, 5],
       [1, 2, 3]])

In [ ]:
# Acima pegamos todas as linhas e colunas da matriz, exceto a coluna e linhas do 2 algoritmo

M[1,:]

array([1, 2, 3])

In [ ]:
# Acima pegamos toda a linha do algoritmo 1

M[:,1]

array([4, 2, 7])

In [ ]:
# Acima pegamos toda a coluna do algoritmo 1